# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-WikiConverter-MediaWiki
version:      0.52
version_from: lib/HTML/WikiConverter/MediaWiki.pm
installdirs:  site
requires:
    HTML::WikiConverter:           0.54
    Test::More:                    0
    URI:                           1.35

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
